# Generated by Django 4.2 on 2023-05-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("levelupapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="levelupapi.gametype",
            ),
        ),
    ]
